### ISSUE TITLE
Needs more poggers

### ISSUE THREAD

**Issue by Grazen0** [Million900o/jason.db#4]
Add a .poggers extension 👀

**Comment by alexanderpaolini** [comment]
you could just use .poggers and renameFile as false

**Comment by Grazen0** [comment]
perhaps

**Comment by alexanderpaolini** [comment]
What should I do to increase poggers?
I can't change jason's db file extention to .poggers

**Comment by Grazen0** [comment]
How bout I make a PoggersCollection
